#server:
#  port: 8081
spring:
  datasource:
    initialization-mode: always
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/blog
    hikari:
      maximum-pool-size: 12
      connection-timeout: 60000
      minimum-idle: 10
      idle-timeout: 500000
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
#    database-platform: org.hibernate.dialect.MySQLDialect