#server:
#  port: 8081
spring:
  profiles:
    active: pro
  thymeleaf:
    cache: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true

  servlet:
    multipart:
      max-file-size: 10MB
server:
  servlet:
    context-path: /blog